# SwiftLint Configuration for Momentum Finance

# Rules to include
included:
  - Shared
  - iOS
  - macOS

# Rules to exclude
excluded:
  - Carthage
  - Pods
  - .build
  - DerivedData

# Rules that are disabled
disabled_rules:
  - trailing_whitespace
  - todo
  - type_name
  - force_unwrapping
  - no_force_unwrapping
  - file_header

# Rules that are optional (warnings)
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - first_where
  - identical_operands
  - implicit_return
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - lower_acl_than_parent
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - nimble_operator
  - nslocalizedstring_key
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  - required_enum_case
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - strict_fileprivate
  - switch_case_on_newline
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - xct_specific_matcher
  - yoda_condition

# Custom rules configuration
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_body_length:
  warning: 60
  error: 100

function_parameter_count:
  warning: 6
  error: 8

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 500
  error: 800
  ignore_comment_only_lines: true

cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: true

nesting:
  type_level:
    warning: 3
  function_level:
    warning: 5

identifier_name:
  min_length:
    warning: 1
  max_length:
    warning: 60
  excluded:
    - id
    - URL
    - url

large_tuple:
  warning: 3
  error: 4

# Custom reporter (use xcode for better integration)
reporter: "xcode"

# File header template
file_header:
  required_pattern: |
                    \/\/ filepath: .*
                    \/\/ Momentum Finance - Personal Finance App
                    \/\/ Copyright © \d{4} Momentum Finance\. All rights reserved\.

# Custom rules
custom_rules:
  # Disable swiftdata_import for now - models already have correct imports
  # swiftdata_import:
  #   included: ".*Models/.*\\.swift"
  #   name: "SwiftData Import"
  #   regex: "^(?!.*import SwiftData).*@Model"
  #   message: "Model files should import SwiftData"
  #   severity: warning

  # Enforce MVVM pattern for ViewModels
  viewmodel_observable:
    included: ".*ViewModels/.*\\.swift"
    name: "ViewModel Observable"
    regex: "@MainActor\\s+class.*ViewModel.*ObservableObject"
    message: "ViewModels should be @MainActor and conform to ObservableObject"
    severity: warning

  # Discourage force unwrapping in production code
  no_force_unwrapping:
    name: "Force Unwrapping"
    regex: "\\!(?![\\s]*\\/\\/)"
    message: "Avoid force unwrapping - use optional binding or guard statements"
    severity: warning

  # Encourage proper error handling
  todo_fixme:
    name: "TODO and FIXME"
    regex: "(TODO|FIXME)"
    message: "TODO and FIXME should be resolved before release"
    severity: warning
    
  # Ensure proper logging usage
  print_usage:
    name: "Print Usage"
    regex: "print\\("
    message: "Use Logger instead of print() for better debugging"
    severity: warning

# Analyzer rules
analyzer_rules:
  - explicit_self
  - unused_import
  - unused_declaration
