#!/bin/bash

# Quick Fix for AI Enhancement System - Simple Pattern Counter
# Streamlined helper that generates enhancement reports and safe auto-apply scripts

set -eo pipefail

# Color codes for output
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'
readonly PURPLE='\033[0;35m'
readonly CYAN='\033[0;36m'
readonly NC='\033[0m' # No Color

# Logging helpers
print_header() { echo -e "${PURPLE}[AI-ENHANCE]${NC} ${CYAN}$1${NC}"; }
print_success() { echo -e "${GREEN}✅ $1${NC}"; }
print_status() { echo -e "${BLUE}🔄 $1${NC}"; }
print_warning() { echo -e "${YELLOW}⚠️  $1${NC}"; }
print_error() { echo -e "${RED}❌ $1${NC}"; }

# Resolve repository root relative to this script unless CODE_DIR is already exported
readonly CODE_DIR="${CODE_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
readonly ENHANCEMENT_DIR="${CODE_DIR}/Documentation/Enhancements"
readonly BACKUP_ROOT="${CODE_DIR}/.autofix_backups"

mkdir -p "${ENHANCEMENT_DIR}"
mkdir -p "${BACKUP_ROOT}"

# Generate a lightweight enhancement report and safe auto-apply script
analyze_project_simple() {
	local project_name="$1"
	local project_path="${CODE_DIR}/Projects/${project_name}"

	if [[ ! -d ${project_path} ]]; then
		print_error "Project ${project_name} not found at ${project_path}"
		return 1
	fi

	print_header "Running AI Enhancement Analysis for ${project_name}"

	(
		cd "${project_path}" || exit 1

		local enhancement_file="${ENHANCEMENT_DIR}/${project_name}_ai_enhancements.md"
		local auto_apply_script="${ENHANCEMENT_DIR}/${project_name}_safe_enhancements.sh"

		local swift_files total_lines
		swift_files=$(find . -type f -name "*.swift" | wc -l | tr -d ' ')
		total_lines=$(find . -type f -name "*.swift" -exec wc -l {} + 2>/dev/null | awk '{sum += $1} END {print sum+0}')

		cat >"${enhancement_file}" <<EOF
# 🚀 AI Enhancement Analysis - ${project_name}
*Generated: $(date)*

## 📊 Project Metrics
- **Swift Files:** ${swift_files}
- **Total Lines:** ${total_lines}
- **Project Type:** iOS/macOS Application
- **Analysis Status:** ✅ Complete

## 🎯 Recommended Enhancements

### 🤖 Auto-Applicable (SAFE)
These enhancements can be applied automatically with backup protection:

1. **Code Formatting & Style**  
   SwiftFormat, import organization, whitespace cleanup  
   **Risk:** SAFE - Auto-apply ready
2. **Documentation Templates**  
   Add doc comment placeholders for functions  
   **Risk:** SAFE - Auto-apply ready
3. **Performance Touch-Ups**  
   Basic collection and string optimization templates  
   **Risk:** SAFE - Auto-apply ready

### 👨‍💻 Manual Review Recommended

1. **Architecture Improvements (MEDIUM)** – Evaluate MVVM separation and dependency injection.
2. **UI/UX Enhancements (MEDIUM)** – Audit accessibility, theming, and consistency.
3. **Security Enhancements (HIGH)** – Harden keychain usage, networking, and validation.
4. **Testing Strategy (MEDIUM)** – Expand unit/UI coverage and add performance tests.

## 📈 Expected Benefits
- Code Quality: ⬆️ Improved
- Maintainability: ⬆️ Enhanced
- Performance: ⬆️ Optimized
- Security: ⬆️ Strengthened
- Accessibility: ⬆️ More compliant

## 🔄 Next Steps
1. Run the safe auto-apply script.
2. Review manual recommendations with the team.
3. Implement prioritized items.
4. Re-run analysis after major code changes.

---
*AI Enhancement System - Making your code better, safely*
EOF

		cat >"${auto_apply_script}" <<'EOF'
#!/bin/bash
# Safe Auto-Apply Enhancements generated by ai_enhancement_simple.sh

set -eo pipefail

log() { echo "[AUTO-ENHANCE] $1"; }

log "Applying safe enhancements..."

if command -v swiftformat &>/dev/null; then
	log "Running SwiftFormat..."
	swiftformat . --config .swiftformat 2>/dev/null || log "SwiftFormat encountered warnings"
else
	log "SwiftFormat not installed; skipping format step"
fi

log "Removing trailing whitespace..."
find . -type f -name "*.swift" -exec sed -i.bak 's/[[:space:]]*$//' {} +
find . -type f -name "*.swift.bak" -delete

log "Providing documentation templates (idempotent)..."
find . -type f -name "*.swift" -exec sed -i.bak '/^[[:space:]]*func .*{/i \
    /// <#Description#>\
    /// - Returns: <#description#>\
' {} + 2>/dev/null || true
find . -type f -name "*.swift.bak" -delete

log "Safe enhancements completed."
EOF

		chmod +x "${auto_apply_script}"

		print_success "Enhancement analysis complete!"
		print_status "📄 Report saved to ${enhancement_file}"
		print_status "🤖 Auto-apply script saved to ${auto_apply_script}"

		echo ""
		echo "📋 Quick Summary:"
		echo "   📱 Project: ${project_name}"
		echo "   📄 Swift files: ${swift_files}"
		echo "   📏 Lines of code: ${total_lines}"
		echo "   🎯 Enhancements: Safe auto-apply + manual review"
		echo ""
		echo "🚀 Next: Run ./master_automation.sh enhance auto-apply ${project_name}"
	)
}

# Apply the generated safe enhancements with automatic backups
auto_apply_safe_enhancements() {
	local project_name="$1"
	local project_path="${CODE_DIR}/Projects/${project_name}"
	local auto_apply_script="${ENHANCEMENT_DIR}/${project_name}_safe_enhancements.sh"

	if [[ ! -d ${project_path} ]]; then
		print_error "Project ${project_name} not found at ${project_path}"
		return 1
	fi

	if [[ ! -f ${auto_apply_script} ]]; then
		print_error "No auto-apply script found for ${project_name}. Run analyze first."
		return 1
	fi

	print_header "Auto-applying safe enhancements for ${project_name}"

	local timestamp
	timestamp=$(date +%Y%m%d_%H%M%S)
	local backup_path="${BACKUP_ROOT}/${project_name}_enhance_${timestamp}"

	print_status "Creating backup at ${backup_path}..."
	mkdir -p "${backup_path}"
	cp -R "${project_path}" "${backup_path}/"
	print_success "Backup created"

	(
		cd "${project_path}" || exit 1
		if bash "${auto_apply_script}"; then
			print_success "Safe enhancements applied successfully!"

			rm -rf "${backup_path}"
			print_status "Backup removed after success"

			echo ""
			echo "🎉 Enhancement Summary:"
			echo "   ✅ Code formatting applied"
			echo "   ✅ Trailing whitespace removed"
			echo "   ✅ Documentation templates added"
			echo ""
			echo "📋 Next: Review manual enhancement recommendations"
		else
			print_error "Enhancement failed - restoring backup"
			rm -rf "${project_path}"
			cp -R "${backup_path}/${project_name}" "${CODE_DIR}/Projects/"
			rm -rf "${backup_path}"
			return 1
		fi
	)
}

# Entry point
case "${1:-help}" in
analyze)
	if [[ -n ${2-} ]]; then
		analyze_project_simple "$2"
	else
		print_error "Usage: $0 analyze <project_name>"
		exit 1
	fi
	;;
analyze-all)
	for project in CodingReviewer HabitQuest MomentumFinance; do
		if [[ -d "${CODE_DIR}/Projects/${project}" ]]; then
			analyze_project_simple "${project}"
			echo ""
		fi
	done
	;;
auto-apply)
	if [[ -n ${2-} ]]; then
		auto_apply_safe_enhancements "$2"
	else
		print_error "Usage: $0 auto-apply <project_name>"
		exit 1
	fi
	;;
auto-apply-all)
	for project in CodingReviewer HabitQuest MomentumFinance; do
		if [[ -d "${CODE_DIR}/Projects/${project}" ]]; then
			auto_apply_safe_enhancements "${project}"
			echo ""
		fi
	done
	;;
help | *)
	echo "🤖 AI Enhancement System - Simple & Reliable"
	echo ""
	echo "Commands:"
	echo "  analyze <project>     # Analyze project for AI enhancements"
	echo "  analyze-all          # Analyze all default projects"
	echo "  auto-apply <project> # Apply safe enhancements with backup"
	echo "  auto-apply-all       # Apply to all default projects"
	echo ""
	echo "Examples:"
	echo "  $0 analyze HabitQuest"
	echo "  $0 auto-apply HabitQuest"
	echo "  $0 analyze-all"
	;;
esac
