#!/bin/bash
# API Documentation Generator
# Generates comprehensive API documentation for all Swift projects

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

WORKSPACE_ROOT="${WORKSPACE_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)}"
DOCS_OUTPUT="${WORKSPACE_ROOT}/Documentation/API"

print_header() {
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${BLUE}  $1${NC}"
    echo -e "${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

# Check for documentation tools
check_dependencies() {
    print_header "Checking Dependencies"

    local has_tools=true

    if command -v jazzy &>/dev/null; then
        print_success "jazzy found: $(jazzy --version)"
    else
        print_warning "jazzy not found - install with: gem install jazzy"
        has_tools=false
    fi

    if command -v sourcedocs &>/dev/null; then
        print_success "sourcedocs found"
    else
        print_warning "sourcedocs not found - install with: brew install sourcedocs"
    fi

    if [ "$has_tools" = false ]; then
        print_error "Missing required tools. Install jazzy to continue."
        return 1
    fi

    return 0
}

# Generate documentation for a project using jazzy
generate_jazzy_docs() {
    local project_dir=$1
    local project_name
    project_name=$(basename "$project_dir")

    print_header "Generating Documentation: ${project_name}"

    cd "$project_dir" || return 1

    # Find xcodeproj or Package.swift
    local xcodeproj
    xcodeproj=$(find . -maxdepth 1 -name "*.xcodeproj" | head -1)

    local output_dir="${DOCS_OUTPUT}/${project_name}"
    mkdir -p "$output_dir"

    if [ -n "$xcodeproj" ]; then
        # Xcode project documentation
        local scheme
        scheme=$(basename "$xcodeproj" .xcodeproj)

        print_success "Documenting Xcode project: ${scheme}"

        jazzy \
            --clean \
            --author "Quantum Workspace" \
            --module "${project_name}" \
            --output "$output_dir" \
            --xcodebuild-arguments -scheme,"${scheme}" \
            --min-acl public \
            --theme fullwidth \
            2>&1 | grep -v "warning:" || true

    elif [ -f "Package.swift" ]; then
        # Swift Package documentation
        print_success "Documenting Swift Package: ${project_name}"

        jazzy \
            --clean \
            --author "Quantum Workspace" \
            --module "${project_name}" \
            --output "$output_dir" \
            --build-tool-arguments -Xswiftc,-swift-version,-Xswiftc,5 \
            --min-acl public \
            --theme fullwidth \
            2>&1 | grep -v "warning:" || true
    else
        print_warning "No project file found"
        return 1
    fi

    # Create index file
    cat >"${output_dir}/../${project_name}_API.md" <<EOF
# ${project_name} API Documentation

**Generated:** $(date)

## Overview

This is the API documentation for the ${project_name} project.

## Documentation Links

- [Full API Documentation](${project_name}/index.html)

## Quick Reference

### Public Interfaces

Run the following to see all public interfaces:

\`\`\`bash
grep -r "public " ${project_dir} --include="*.swift" | grep -E "(class|struct|enum|protocol|func|var|let)" | head -20
\`\`\`

## Usage Examples

See the [Examples](../Examples/${project_name}/) directory for usage examples.

## Architecture

See [ARCHITECTURE.md](../../ARCHITECTURE.md) for overall architecture patterns.

---

*Generated by API Documentation Generator on $(date)*
EOF

    print_success "Documentation generated: ${output_dir}"

    return 0
}

# Generate manual documentation for projects without build setup
generate_manual_docs() {
    local project_dir=$1
    local project_name
    project_name=$(basename "$project_dir")

    print_header "Manual Documentation: ${project_name}"

    local output_file="${DOCS_OUTPUT}/${project_name}_API.md"

    cat >"$output_file" <<EOF
# ${project_name} API Reference

**Generated:** $(date)
**Type:** Manual Documentation

## Public API Overview

EOF

    # Find all public declarations
    print_success "Extracting public interfaces..."

    # Classes
    {
        echo "### Public Classes"
        echo ""
    } >>"$output_file"
    grep -rh "public class" "$project_dir" --include="*.swift" 2>/dev/null |
        sed 's/^[[:space:]]*//' |
        sed 's/{.*//' |
        while IFS= read -r line; do
            echo "- \`$line\`" >>"$output_file"
        done || echo "- None found" >>"$output_file"
    echo "" >>"$output_file"

    # Structs
    {
        echo "### Public Structs"
        echo ""
    } >>"$output_file"
    grep -rh "public struct" "$project_dir" --include="*.swift" 2>/dev/null |
        sed 's/^[[:space:]]*//' |
        sed 's/{.*//' |
        while IFS= read -r line; do
            echo "- \`$line\`" >>"$output_file"
        done || echo "- None found" >>"$output_file"
    echo "" >>"$output_file"

    # Enums
    {
        echo "### Public Enums"
        echo ""
    } >>"$output_file"
    grep -rh "public enum" "$project_dir" --include="*.swift" 2>/dev/null |
        sed 's/^[[:space:]]*//' |
        sed 's/{.*//' |
        while IFS= read -r line; do
            echo "- \`$line\`" >>"$output_file"
        done || echo "- None found" >>"$output_file"
    echo "" >>"$output_file"

    # Protocols
    {
        echo "### Public Protocols"
        echo ""
    } >>"$output_file"
    grep -rh "public protocol" "$project_dir" --include="*.swift" 2>/dev/null |
        sed 's/^[[:space:]]*//' |
        sed 's/{.*//' |
        while IFS= read -r line; do
            echo "- \`$line\`" >>"$output_file"
        done || echo "- None found" >>"$output_file"
    echo "" >>"$output_file"

    cat >>"$output_file" <<EOF

## Usage

For detailed usage examples, see the source files in:
\`${project_dir}\`

## Architecture Notes

This project follows the Quantum Workspace architecture patterns. See [ARCHITECTURE.md](../../ARCHITECTURE.md) for details.

---

*For full HTML documentation, run:*
\`\`\`bash
jazzy --module ${project_name} --output Documentation/API/${project_name}
\`\`\`
EOF

    print_success "Manual documentation created: $output_file"
}

# Generate documentation index
generate_documentation_index() {
    print_header "Generating Documentation Index"

    local index_file="${DOCS_OUTPUT}/README.md"

    cat >"$index_file" <<EOF
# API Documentation Index

**Last Updated:** $(date)

This directory contains automatically generated API documentation for all Quantum Workspace projects.

## Projects

EOF

    # List all documented projects
    for project_dir in "${WORKSPACE_ROOT}"/Projects/*/; do
        if [ -d "$project_dir" ]; then
            local project_name
            project_name=$(basename "$project_dir")

            # Check if documentation exists
            if [ -d "${DOCS_OUTPUT}/${project_name}" ] || [ -f "${DOCS_OUTPUT}/${project_name}_API.md" ]; then
                echo "### ${project_name}" >>"$index_file"
                echo "" >>"$index_file"

                if [ -d "${DOCS_OUTPUT}/${project_name}" ]; then
                    echo "- [Full API Documentation](${project_name}/index.html)" >>"$index_file"
                fi

                if [ -f "${DOCS_OUTPUT}/${project_name}_API.md" ]; then
                    echo "- [Quick Reference](${project_name}_API.md)" >>"$index_file"
                fi

                echo "" >>"$index_file"
            fi
        fi
    done

    cat >>"$index_file" <<'EOF'

## Documentation Standards

All public APIs should include:

1. **Clear documentation comments** using `///` syntax
2. **Parameter descriptions** using `- Parameter name: description`
3. **Return value descriptions** using `- Returns: description`
4. **Example usage** where appropriate
5. **Thread-safety notes** for concurrent code

## Regenerating Documentation

To regenerate all documentation:

```bash
./Tools/Automation/generate_api_docs.sh
```

To document a specific project:

```bash
cd Projects/YourProject
jazzy --module YourProject
```

## Tools Used

- **jazzy**: Primary documentation generator for Swift
- **sourcedocs**: Alternative documentation tool (optional)

Install with:
```bash
gem install jazzy
brew install sourcedocs
```

---

*Auto-generated by API Documentation Generator*
EOF

    print_success "Documentation index created: $index_file"
}

# Main execution
main() {
    print_header "API Documentation Generator"
    echo "Workspace: ${WORKSPACE_ROOT}"
    echo "Output: ${DOCS_OUTPUT}"
    echo ""

    mkdir -p "$DOCS_OUTPUT"

    # Check dependencies
    if ! check_dependencies; then
        print_warning "Falling back to manual documentation extraction"

        # Generate manual docs for all projects
        for project_dir in "${WORKSPACE_ROOT}"/Projects/*/; do
            if [ -d "$project_dir" ]; then
                generate_manual_docs "$project_dir" || true
            fi
        done
    else
        # Generate full jazzy docs
        for project_dir in "${WORKSPACE_ROOT}"/Projects/*/; do
            if [ -d "$project_dir" ]; then
                generate_jazzy_docs "$project_dir" || generate_manual_docs "$project_dir" || true
            fi
        done
    fi

    echo ""
    generate_documentation_index

    print_header "Documentation Generation Complete"
    print_success "Documentation available in: ${DOCS_OUTPUT}"
}

main "$@"
