name: Swift CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Swift
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: '6.0'
        
    - name: Install SwiftLint
      run: brew install swiftlint
      
    - name: Install SwiftFormat
      run: brew install swiftformat
    
    - name: Format Swift code
      run: swiftformat . --config .swiftformat || echo "SwiftFormat config not found, using defaults"
    
    - name: Lint Swift code
      run: swiftlint --strict
    
    - name: Build
      run: |
        if [ -f "Package.swift" ]; then
          echo "Building Swift Package..."
          swift build -v
        else
          echo "Building Xcode project..."
          xcodebuild -project HabitQuest.xcodeproj \
                     -scheme HabitQuest \
                     -destination 'platform=iOS Simulator,name=iPhone 15' \
                     build
        fi
    
    - name: Run tests
      run: |
        if [ -f "Package.swift" ]; then
          echo "Running Swift Package tests..."
          swift test -v
        else
          echo "Running Xcode tests..."
          xcodebuild -project HabitQuest.xcodeproj \
                     -scheme HabitQuest \
                     -destination 'platform=iOS Simulator,name=iPhone 15' \
                     test
        fi
