#!/bin/bash

# Documentation Automation Setup Script
# Sets up automated documentation maintenance workflows

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
DOCS_DIR="$SCRIPT_DIR"

# Configuration
CRON_FILE="$HOME/.documentation_cron"
MAINTENANCE_SCRIPT="$DOCS_DIR/docs_maintenance.sh"
UPDATE_SCRIPT="$DOCS_DIR/update_docs.sh"

log() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') - SETUP: $1"
}

# Install required tools
install_tools() {
    log "Installing required documentation tools..."

    if command -v brew &>/dev/null; then
        brew install markdownlint-cli linkchecker jq 2>/dev/null || true
    fi

    # Install Python dependencies for documentation processing
    if [ -f "$PROJECT_ROOT/requirements.txt" ]; then
        pip3 install -r "$PROJECT_ROOT/requirements.txt" 2>/dev/null || true
    fi

    log "Tool installation completed"
}

# Set up cron jobs for automated documentation maintenance
setup_cron_jobs() {
    log "Setting up automated documentation workflows..."

    # Create cron entries
    cat >"$CRON_FILE" <<EOF
# Documentation Maintenance Cron Jobs
# Generated by setup_docs_automation.sh on $(date)

# Daily documentation validation (6 AM)
0 6 * * * $MAINTENANCE_SCRIPT >> $DOCS_DIR/logs/cron_maintenance.log 2>&1

# Weekly documentation updates (Sundays 2 AM)
0 2 * * 0 $UPDATE_SCRIPT >> $DOCS_DIR/logs/cron_updates.log 2>&1

# Monthly comprehensive validation (1st of month 3 AM)
0 3 1 * * $MAINTENANCE_SCRIPT --comprehensive >> $DOCS_DIR/logs/cron_monthly.log 2>&1
EOF

    # Install cron jobs
    if command -v crontab &>/dev/null; then
        crontab "$CRON_FILE"
        log "Cron jobs installed successfully"
    else
        log "WARNING: crontab not available. Manual cron setup required."
        log "Please run: crontab $CRON_FILE"
    fi
}

# Create initial documentation structure
create_docs_structure() {
    log "Creating documentation structure..."

    mkdir -p "$DOCS_DIR"/{examples,tutorials,api,logs,reports}

    # Create README for docs
    cat >"$DOCS_DIR/README.md" <<'EOF'
# Documentation

This directory contains automated documentation maintenance and validation tools.

## Structure

- `docs_maintenance.sh` - Main validation and maintenance script
- `update_docs.sh` - Documentation update workflow
- `setup_docs_automation.sh` - Automation setup script
- `examples/` - Usage examples
- `tutorials/` - Tutorial documentation
- `api/` - API reference documentation
- `logs/` - Maintenance logs
- `reports/` - Validation reports

## Automation

Documentation maintenance runs automatically via cron jobs:

- **Daily**: Validation and link checking (6 AM)
- **Weekly**: Content updates and API docs refresh (Sunday 2 AM)
- **Monthly**: Comprehensive validation (1st of month 3 AM)

## Manual Usage

```bash
# Run validation
./docs_maintenance.sh

# Update documentation
./update_docs.sh

# Setup automation
./setup_docs_automation.sh
```

## Reports

Check `reports/` directory for validation reports and `logs/` for execution logs.
EOF

    log "Documentation structure created"
}

# Validate setup
validate_setup() {
    log "Validating documentation automation setup..."

    local issues=0

    # Check scripts exist and are executable
    for script in "$MAINTENANCE_SCRIPT" "$UPDATE_SCRIPT"; do
        if [ ! -x "$script" ]; then
            log "ERROR: Script not executable: $script"
            ((issues++))
        fi
    done

    # Check cron setup
    if ! crontab -l | grep -q "docs_maintenance.sh"; then
        log "WARNING: Cron jobs may not be properly installed"
    fi

    # Test basic functionality
    if ! "$MAINTENANCE_SCRIPT" --help 2>/dev/null; then
        log "WARNING: Maintenance script may have issues"
    fi

    if [ $issues -eq 0 ]; then
        log "Documentation automation setup validated successfully"
    else
        log "Found $issues setup issues"
        return 1
    fi
}

# Main setup execution
main() {
    log "Starting documentation automation setup..."

    install_tools
    create_docs_structure
    setup_cron_jobs
    validate_setup

    log "Documentation automation setup completed"
    log "Run './docs_maintenance.sh' to test the setup"
}

# Run main function
main "$@"
